name: Rust

on:
  push:
    branches: "*"
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --all-features --all-targets --verbose
